[parity]
chain = "genesis.json"
base_path = "node0"

[network]
port = 30300
#bootnodes = []

[account]
password = ["node0.pwd"]

[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["http://localhost:8000", "http://localhost:8545"]

[websockets]
port = 8450

[mining]
engine_signer = "0xfe111d8dbc69453337a32b41426011a4bda13fbf"
reseal_on_txs = "none"
force_sealing = true
